version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "myuser", "-d", "mydatabase"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 5s

  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6380:6379"

  app:
    build: .
    container_name: my_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgresql://myuser:mypassword@postgres:5432/mydatabase"
      REDIS_URL: "redis://my_redis:6379/0"
      SECRET_KEY: "mysecretkey"
    ports:
      - "8080:8080"
    command: ["python3", "-m", "app.main"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 5s
  
volumes:
  postgres_data: